include:
  - board: corneish_zen_left//zmk
    snippet: studio-rpc-usb-uart
  - board: corneish_zen_right//zmk
  - board: nice_nano@2.0.0//zmk
    shield: corne_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano@2.0.0//zmk
    shield: corne_right
